name: Nightly Maven Test

on:
  schedule:
    - cron: '0 22 * * *'   # Every day at 10 PM UTC
  workflow_dispatch:       # Optional manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Maven tests in CheckOutFlow
        run: |
          cd CheckOutFlow
          mvn test
